### ISSUE TITLE
Testsuite failure: certs in dev-resources/ssl have expired

### ISSUE THREAD

**Issue by baldurmen** [puppetlabs/clj-rbac-client#56]
Hi,

The certs in dev-resources/ssl have expired, which makes the testsuite fail.

Would it be possible to regenerate them (and possibly, not use an expiration date this time?)

Cheers,

**Comment by jonathannewman** [comment]
Thanks for letting us know.  We will update the certs.

**Comment by jonathannewman** [comment]
Addressed with https://github.com/puppetlabs/clj-rbac-client/pull/57  Thank you!
